### ISSUE TITLE
Errors returning nested information when results are materialise in an entity

### ISSUE THREAD

**Issue by jmcervera** [rom-rb/rom-sql#223] opened 2017-07-12 07:17 UTC
After upgrade rom-sql from 1.2.2 to rom-sql 1.3.3

If have experimented this problem:
I had a method on a repository that returned a collection with a related entity (belongs_to association) being aggregated. 
With the first version the aggregated data was returned as a ROM::Struct, with the upgraded version I get the information returned as a Hash.
I have realised that this occurs when I materialise the result into an Dry::Struct entity.

```ruby
   def intervals(driver, initial_time, final_time)
      aggregate(journey: :ratings)
        .connection_times(driver, initial_time, final_time)
        .map_to(Entities::StateInterval).to_a
    end
```
This now fails returning the journeys as a ROM::Struct 
 ```ruby
   def intervals(driver, initial_time, final_time)
      aggregate(journey: :ratings)
        .connection_times(driver, initial_time, final_time)
        .to_a
    end
```
But this works as expected, I get the return of intervals and nested journeys as ROM:: Structs on both cases.

**Comment by solnic** [comment] 2017-07-12 07:47
Which versions of rom/mapper/repository do you have?

**Comment by jmcervera** [comment] 2017-07-12 08:03
0.5.1

**Comment by jmcervera** [comment] 2017-07-12 08:04
rom (3.3.1)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-initializer (~> 1.3)
      dry-types (~> 0.9, >= 0.9.4)
      rom-mapper (~> 0.5, >= 0.5.1)
    rom-mapper (0.5.1)
      dry-core (~> 0.2, >= 0.2.3)
      dry-equalizer (~> 0.2)
      transproc (~> 1.0)
    rom-repository (1.4.0)
      dry-core (~> 0.3, >= 0.3.1)
      dry-struct (~> 0.3)
      rom (~> 3.3)
      rom-mapper (~> 0.5)
    rom-sql (1.3.3)
      dry-core (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.10, >= 0.10.2)
      rom (~> 3.2, >= 3.2.2)

**Comment by solnic** [comment] 2017-07-12 08:07
@jmcervera pin `rom` to `3.2.3` and `rom-repository` to `1.3.3` for now, this should work for you.

**Comment by jmcervera** [comment] 2017-07-12 08:19
It does not work form me, I'm still receiving raw hashes as the nested objects.

**Comment by solnic** [comment] 2017-07-12 08:23
Can you reproduce this and provide a script I could run and debug?

**Comment by solnic** [comment] 2019-04-19 13:00
Closing due to lack of any activity. Please re-open if this can be reproduced using latest rom/rom-sql version.

**Closed by solnic** 2019-04-19 13:00 UTC
Labels: unconfirmed
