### ISSUE TITLE
NoMethodError: undefined method `associate' for ROM::SQL::Association::OneToMany

### ISSUE THREAD

**Issue by dg-ratiodata** [rom-rb/rom-sql#82] opened 2016-08-29 12:28 UTC
### Setup

The User Repo file.

~~~ruby
require 'script/user'

module Script
  class UserRepo < ROM::Repository[:users]
    relations :departments, :roles

    commands :create, update: :by_pk

    def query(conditions)
      users.where(conditions).as(User)
    end

    def by_id(id)
      users.fetch(id)
    end

    def create_with_department(user)
      command(:create, aggregate(:department), aggregate(:role)).call(user)
    end
  end
end
~~~

Container-file

~~~ruby
require 'rom'
require 'rom/repository'

module Script
  CONTAINER = ROM.container(:sql, 'sqlite::memory') do |conf|
    conf.default.connection.create_table(:users) do
      primary_key :id
      column :name, String, null: false
      foreign_key :department_id, :departments
      foreign_key :role_id, :roles
    end

    conf.default.connection.create_table(:departments) do
      primary_key :id
      column :name, String, null: false
    end

    conf.default.connection.create_table(:roles) do
      primary_key :id
      column :name, String, null: false
    end

    conf.relation(:users) do
      schema(infer: true) do
        associations do
          belongs_to :department
          belongs_to :role
        end
      end
    end

    conf.relation(:departments) do
      schema(infer: true) do
        associations do
          has_many :users
        end
      end
    end

    conf.relation(:roles) do
      schema(infer: true) do
        associations do
          has_many :users
        end
      end
    end
  end
end
~~~

Gemfile.lock

~~~ruby
GEM
  remote: https://rubygems.org/
  specs:
    byebug (9.0.5)
    coderay (1.1.1)
    concurrent-ruby (1.0.2)
    dry-configurable (0.1.7)
      concurrent-ruby (~> 1.0)
    dry-container (0.4.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-equalizer (0.2.0)
    dry-logic (0.3.0)
      dry-container (~> 0.2, >= 0.2.6)
      dry-equalizer (~> 0.2)
    dry-monads (0.1.1)
      dry-equalizer
    dry-types (0.8.1)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1)
      dry-container (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-monads (>= 0.0.1)
      ice_nine (~> 0.11)
      inflecto (~> 0.0.0, >= 0.0.2)
    dry-validation (0.9.5)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-container (~> 0.2, >= 0.2.8)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-types (~> 0.8, >= 0.8.1)
    ice_nine (0.11.2)
    inflecto (0.0.2)
    method_source (0.8.2)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.4.0)
      byebug (~> 9.0)
      pry (~> 0.10)
    rom (2.0.0)
      concurrent-ruby (~> 1.0)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.8)
      rom-mapper (~> 0.4.0)
      rom-support (~> 2.0)
    rom-http (0.5.0)
      dry-equalizer
      dry-types
      rom (~> 2.0)
      thread_safe
    rom-mapper (0.4.0)
      dry-equalizer (~> 0.2)
      rom-support (~> 2.0.0)
      transproc (~> 0.4.0)
    rom-repository (0.3.1)
      rom (~> 2.0)
      rom-mapper (~> 0.4)
      rom-support (~> 2.0)
    rom-sql (0.8.0)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.8)
      rom (~> 2.0)
      rom-support (~> 2.0)
      sequel (~> 4.25)
    rom-support (2.0.0)
      concurrent-ruby (~> 1.0)
      dry-equalizer (~> 0.2)
      transproc (~> 0.4.0)
      wisper (~> 1.6, >= 1.6.0)
    sequel (4.37.0)
    slop (3.6.0)
    sqlite3 (1.3.11)
    thor (0.19.1)
    thread_safe (0.3.5)
    transproc (0.4.0)
    wisper (1.6.1)

PLATFORMS
  ruby

DEPENDENCIES
  dry-equalizer
  dry-types
  dry-validation
  pry
  pry-byebug
  rom-http
  rom-repository
  rom-sql
  sqlite3
  thor

BUNDLED WITH
~~~

### Current behaviour

When I run my script I get the following error:

~~~bash
NoMethodError: undefined method `associate' for #<ROM::SQL::Association::OneToMany:0x000000011ed0b0>
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/plugin/associates.rb:69:in `block in execute'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/plugin/associates.rb:68:in `map'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/plugin/associates.rb:68:in `each'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/plugin/associates.rb:68:in `map'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/plugin/associates.rb:68:in `execute'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/command.rb:110:in `call'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/commands/error_wrapper.rb:12:in `call'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/commands/lazy/create.rb:17:in `call'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/commands/graph.rb:64:in `block in call'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/commands/graph.rb:61:in `map'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/commands/graph.rb:61:in `call'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/commands/composite.rb:18:in `call'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_proxy.rb:14:in `call'
/home/user1/project/lib/script/repos/user_repo.rb:18:in `create_with_department'
/home/user1/project/lib/script/cli_runner.rb:25:in `parse_data'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
~~~

### Expected behaviour

No exception or better error message explaining what I did wrong or documentation how to prevent that error.

**Comment by dg-ratiodata** [comment] 2016-08-29 12:37
Related to #79.

**Comment by dg-ratiodata** [comment] 2016-08-29 12:54
Switching the implementation to create the user first and then update the department, results in a different exception:

~~~ruby
require 'script/container'
require 'script/repos/role_repo'
require 'script/repos/user_repo'
require 'script/repos/department_repo'
require 'script/container'
require  'thor'

module Script
  class CliRunner < Thor
    desc 'parse_data', 'Parse data from files'
    def parse_data
      role_repo = RoleRepo.new(Script::CONTAINER)
      department_repo = DepartmentRepo.new(Script::CONTAINER)
      user_repo = UserRepo.new(Script::CONTAINER)

      employee_role = role_repo.create(name: 'employee')
      manager_role = role_repo.create(name: 'manager')
      department = department_repo.create(name: 'department1')
      user = user_repo.create(name: 'user1')

      department_repo.add_user(name: 'department1', user: user)
      user = user_repo.create(name: 'user1')
      manager = manager_repo.create(name: 'manager1')


    end

    default_command :parse_data
  end
end
~~~

The department repo definition:

~~~ruby
require 'script/department'

module Script
  class DepartmentRepo < ROM::Repository[:departments]
    relations :users

    commands :create, update: :by_pk

    def query(conditions)
      departments.where(conditions).as(Department)
    end

    def by_id(id)
      departments.fetch(id)
    end

    def add_user(department)
      command(:update, aggregate(:users)).all(department)
    end
  end
end
~~~

~~~
NameError: undefined local variable or method `associations' for ROM::SQL::Commands::Update[:users]:Class
Did you mean?  associates
/home/user1/.rvm/gems/ruby-2.3.0/bundler/gems/rom-sql-1c11f057dc0c/lib/rom/sql/plugin/associates.rb:106:in `associates'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:182:in `setup_associates'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:155:in `block in register_command'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-2.0.0/lib/rom/commands/class_interface.rb:73:in `create_class'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:151:in `register_command'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:115:in `visit_relation'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:98:in `visit'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:126:in `block in visit_header'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:126:in `map'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:126:in `visit_header'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:98:in `visit'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:106:in `visit_relation'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:98:in `visit'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:45:in `block in []'
/home/user1/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:133:in `block in fetch_or_store'
/home/user1/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:122:in `fetch'
/home/user1/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:132:in `fetch_or_store'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_compiler.rb:38:in `[]'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository.rb:212:in `compile_command'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository.rb:138:in `block in command'
/home/user1/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:133:in `block in fetch_or_store'
/home/user1/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:122:in `fetch'
/home/user1/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:132:in `fetch_or_store'
/home/user1/.rvm/gems/ruby-2.3.0/gems/rom-repository-0.3.1/lib/rom/repository.rb:137:in `command'
/home/user1/project/lib/script/repos/department_repo.rb:20:in `add_user'
/home/user1/project/lib/script/cli_runner.rb:27:in `parse_data'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/user1/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
bin/script.rb:7:in `<top (required)>'
~~~

**Comment by solnic** [comment] 2016-08-29 13:07
Thanks for this detailed report, that's very helpful. I'll look into that.

**Comment by solnic** [comment] 2016-08-29 14:16
btw:

``` ruby
    def add_user(department)
      command(:update, aggregate(:users)).all(department)
    end
```

^^ should be `:create` instead of `:update` and `call` instead of `all`

**Comment by dg-ratiodata** [comment] 2016-08-30 07:33
@solnic Thanks. If you need more information, don't hesitate to ping me.

**Comment by dg-ratiodata** [comment] 2016-08-30 07:41
BTW: I love the flexibility of `rom`, but it's a bit confusing for beginners. :-) Is there an ongoing discussion about the "style" you should use with `rom` anywhere? I found quite a few different possibilities on the net, which all seem to work. Shall I open another issue for that?

**Comment by solnic** [comment] 2016-08-30 12:15
> I love the flexibility of rom, but it's a bit confusing for beginners. :-)

This will improve once rom-repository reaches 1.0.0 :)

> Is there an ongoing discussion about the "style" you should use with rom anywhere?

Nope, but feel free to start one on discuss.rom-rb.org

> What was a bit problematic for me, is the order in which things needs to be initialized. I was not able to reproduce the problem I had, along with the problems above I faced a ROM::Repository-constant missing error. After adding require 'rom/repository' to my repo-files the error went away. I cannot provide more information on that topic for you. Does it makes sense to open a ticket for that?

Nothing requires `rom/repository` for you, so you need to require that file yourself. This is not a bug. Require What You Require™ :)

**Comment by dg-ratiodata** [comment] 2016-09-01 07:24
> Nothing requires rom/repository for you, so you need to require that file yourself. 

Ah, ok. Good to know. Was not aware of that. Thanks.

**Comment by dg-ratiodata** [comment] 2016-09-01 07:24
> Nothing requires rom/repository for you, so you need to require that file yourself. 

Ah, ok. Good to know. Was not aware of that. Thanks.

**Comment by solnic** [comment] 2016-09-30 22:42
I'm closing this one. Feel free to re-open or report a new issue if something needs to be done or discussed.

**Closed by solnic** 2016-09-30 22:42 UTC
