### ISSUE TITLE
undefined method `indexes' for nil:NilClass (clustered-mode Puma)

### ISSUE THREAD

**Issue by nbulaj** [rom-rb/rom-sql#227] opened 2017-07-20 14:54 UTC
Hi @solnic . I have an almost empty Rails application with the next gems stack:

```ruby
gem 'rails', '5.1.2'
gem 'pg', '~> 0.20'
gem 'puma', '~> 3.7' # (3.9.1)

gem 'rom', '4.0.0.beta2'
gem 'rom-rails', '1.0.0.beta1'
gem 'rom-sql', '2.0.0.beta2'
```

Also I have `Users` relation like this:

```ruby
class Users < ROM::Relation[:sql]
  schema infer: true
end
```

Initializer looks like:

```ruby
ROM::Rails::Railtie.configure do |config|
  config.gateways[:default] = [:sql, ENV.fetch('DATABASE_URL')]
end
```

Nothing special as you can see. When I start rails server and trying to access an app I get the folowwing error:

> undefined method `indexes' for nil:NilClass
>
> methods = schema.indexes.each_with_object([]) do |index, generated|
> rom-sql (2.0.0.beta2) lib/rom/plugins/relation/sql/auto_restrictions.rb:42:in `restriction_methods'

But after some time (~5 seconds) I refresh the page and everything works. I think that problem correlates with the Puma server, because when I run application in a single-mode - everything is OK, but when I use clustered-mode with some number of workers - the problem occurs. 

As I can understand it is a problem with ROM-rb database connections, that is related to `preload_app!` and `on_worker_boot` functionality. There must be something like it is done for ActiveRecord:

```ruby
on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

A little bit similar question was asked on [StackOverflow](https://stackoverflow.com/q/32153255/5695614).

What do you think about this? Maybe there are some documentation about using ROM-rb with Puma server?

Some additional info:

**Puma config:**

```ruby
threads_count = ENV.fetch('MAX_THREADS') { 5 }.to_i
threads threads_count, threads_count

port ENV.fetch('PORT') { 3000 }
environment ENV.fetch('RAILS_ENV') { 'development' }

preload_app!

workers ENV.fetch('WEB_CONCURRENCY') { 4 }
worker_timeout ENV.fetch('WEB_TIMEOUT') { 60 }.to_i

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart

```

**Stack trace**

```
rom-sql (2.0.0.beta2) lib/rom/plugins/relation/sql/auto_restrictions.rb:42:in `restriction_methods'
rom-sql (2.0.0.beta2) lib/rom/plugins/relation/sql/auto_restrictions.rb:34:in `block in <module:AutoRestrictions>'
rom-core (4.0.0.beta2) lib/rom/support/notifications.rb:49:in `trigger'
rom-core (4.0.0.beta2) lib/rom/support/notifications.rb:21:in `block in trigger'
rom-core (4.0.0.beta2) lib/rom/support/notifications.rb:20:in `each'
rom-core (4.0.0.beta2) lib/rom/support/notifications.rb:20:in `trigger'
rom-core (4.0.0.beta2) lib/rom/setup/finalize/finalize_relations.rb:93:in `build_relation'
rom-core (4.0.0.beta2) lib/rom/setup/finalize/finalize_relations.rb:48:in `block (2 levels) in run!'
rom-core (4.0.0.beta2) lib/rom/setup/finalize/finalize_relations.rb:31:in `each'
rom-core (4.0.0.beta2) lib/rom/setup/finalize/finalize_relations.rb:31:in `block in run!'
rom-core (4.0.0.beta2) lib/rom/relation_registry.rb:7:in `initialize'
rom-core (4.0.0.beta2) lib/rom/registry.rb:22:in `new'
rom-core (4.0.0.beta2) lib/rom/registry.rb:22:in `new'
rom-core (4.0.0.beta2) lib/rom/setup/finalize/finalize_relations.rb:30:in `run!'
rom-core (4.0.0.beta2) lib/rom/setup/finalize.rb:86:in `load_relations'
rom-core (4.0.0.beta2) lib/rom/setup/finalize.rb:62:in `run!'
rom-core (4.0.0.beta2) lib/rom/create_container.rb:34:in `finalize'
rom-core (4.0.0.beta2) lib/rom/create_container.rb:11:in `initialize'
rom-core (4.0.0.beta2) lib/rom/create_container.rb:53:in `initialize'
rom-core (4.0.0.beta2) lib/rom/create_container.rb:58:in `new'
rom-core (4.0.0.beta2) lib/rom/create_container.rb:58:in `container'
rom-rails (1.0.0.beta1) lib/rom/rails/railtie.rb:79:in `create_container'
railties (5.1.2) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.2) lib/rails/railtie.rb:185:in `method_missing'
rom-rails (1.0.0.beta1) lib/rom/rails/railtie.rb:44:in `block in <class:Railtie>'
activesupport (5.1.2) lib/active_support/callbacks.rb:413:in `instance_exec'
activesupport (5.1.2) lib/active_support/callbacks.rb:413:in `block in make_lambda'
```

**Comment by nbulaj** [comment] 2017-07-20 16:10
Whooops, looks like in a single (thread) mode I have this error too. The problem is connected with the threads as far as I see from the stack trace (puma `thread_spawn` method)...

**Comment by solnic** [comment] 2017-07-20 16:21
Does it happen in production env too?

**Comment by nbulaj** [comment] 2017-07-21 07:25
@solnic no, with `RAILS_ENV=production` it works (in any case during all my attempts to reproduce the problem)

**Comment by solnic** [comment] 2017-07-21 08:03
@flash-gordon any idea why `klass.schema` becomes nil after rails removes/re-adds relation class and we finalize it again? It happens when we trigger [this setup event](https://github.com/rom-rb/rom/blob/master/core/lib/rom/setup/finalize/finalize_relations.rb#L95).

**Comment by solnic** [comment] 2017-07-21 08:09
@nbulaj FYI this is due to code reloading in dev mode and possibly because rom setup/finalization is not thread-safe, but I'm not sure.

**Comment by nbulaj** [comment] 2017-07-21 12:58
@solnic I think you are right about thread-safety, because this error occurs randomly on a long-running app with thread-only Puma in the development mode.

> rom-sql (2.0.0.beta2) lib/rom/plugins/relation/sql/auto_restrictions.rb:42:in `restriction_methods'
> rom-sql (2.0.0.beta2) lib/rom/plugins/relation/sql/auto_restrictions.rb:34:in `block in <module:AutoRestrictions>'
> rom-core (4.0.0.beta2) lib/rom/support/notifications.rb:49:in `trigger'
> ...
> puma (3.9.1) lib/puma/server.rb:435:in `process_client'
> puma (3.9.1) lib/puma/server.rb:299:in `block in run'
> puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by flash-gordon** [comment] 2017-07-21 16:09
@solnic this was fixed in master https://github.com/rom-rb/rom/commit/7d24c01b40aa89710c6466b212fb6eaefb4396b8

**Comment by flash-gordon** [comment] 2017-07-21 16:49
Atm the setup process is not thread safe, this is usually OK though I must admit it's kind of reckless and may lead to occasional glitches which would be hard to reproduce. I guess we could serialize the whole setup block, it should be safe to do. On the application level, I'd recommend to setup the container in production before the fork happen, i.e.
```
before_fork do
  # setup rom container
end
```
However, I'm not sure what strategy would be better in development with the rails reloading mechanism in action.

**Comment by flash-gordon** [comment] 2017-07-21 16:57
@nbulaj could you check it on rom & rom-sql from master, please?

**Comment by nbulaj** [comment] 2017-07-22 12:02
@flash-gordon I will try to ASAP

**Comment by nbulaj** [comment] 2017-07-24 07:32
@flash-gordon can't use master branches:

```ruby
gem 'rom', git: 'https://github.com/rom-rb/rom.git'
gem 'rom-rails', git: 'https://github.com/rom-rb/rom-rails.git'
gem 'rom-sql', git: 'https://github.com/rom-rb/rom-sql.git'
```

Bundler

> $ bundle update
> Fetching https://github.com/rom-rb/rom.git
> Fetching https://github.com/rom-rb/rom-rails.git
> Fetching https://github.com/rom-rb/rom-sql.git
> Fetching gem metadata from https://rubygems.org/............
> Fetching version metadata from https://rubygems.org/...
> Fetching dependency metadata from https://rubygems.org/..
> Resolving dependencies...
> Bundler could not find compatible versions for gem "dry-types":
>   In Gemfile:
>     rom-sql was resolved to 2.0.0.beta3, which depends on
>       dry-types (>= 0.11.1, ~> 0.11)
> 
> Could not find gem 'dry-types (>= 0.11.1, ~> 0.11)', which is required by gem 'rom-sql', in any of the sources.

If I try to use only `master` rom:

```ruby
gem 'rom', git: 'https://github.com/rom-rb/rom.git'
gem 'rom-rails', '1.0.0.beta1'
gem 'rom-sql', '2.0.0.beta2'
gem 'rom-repository', '2.0.0.beta2'
```

Then I get the following error:

> $ rails s
> /home/bulaj/.rvm/gems/ruby-2.4.1/bundler/gems/rom-f8759cd87503/mapper/lib/rom/struct_compiler.rb:10:in 'require': cannot load such file -- rom/attribute (LoadError)
> from /home/bulaj/.rvm/gems/ruby-2.4.1/bundler/gems/rom-f8759cd87503/mapper/lib/rom/struct_compiler.rb:10:in '<top (required)>'

What am I doing wrong?

**Comment by flash-gordon** [comment] 2017-07-24 07:49
ugh, right, it's not straightforward
Try this
```ruby
gem 'dry-types', git: 'https://github.com/dry-rb/dry-types.git'

gem 'rom', git: 'https://github.com/rom-rb/rom' do
  gem 'rom-core'
  gem 'rom-mapper'
  gem 'rom-repository'
end

gem 'rom-sql', git: 'https://github.com/rom-rb/rom-sql.git'
```

**Comment by nbulaj** [comment] 2017-07-24 08:02
You forgot about `gem 'rom-rails', git: 'https://github.com/rom-rb/rom-rails.git'` :)

Now everything is ok. I checked my application both in `dev` and `production` envs - everything seems to be good :+1: (for every Puma mode). So waiting for the release.

I think that something like this would be better to place in some section of the official ROM-rb documentation:

> On the application level, I'd recommend to setup the container in production before the fork happen ..
>
> before_fork do
>   setup rom container
>end

What do you think?

**Comment by flash-gordon** [comment] 2017-07-27 20:02
@nbulaj right, though you need also disconnect Sequel's pool before forking, Sequel is not fork-safe. This usually means calling `container.gateways[:default].connection.disconnect`, see https://github.com/jeremyevans/sequel/issues/691 for more on this

**Comment by nbulaj** [comment] 2017-07-27 20:05
Yeah, I saw the same advice on StackOverflow. Thanks! So I think we can close this issue

**Comment by solnic** [comment] 2017-07-28 08:35
OK I'm gonna close this but I will keep in mind thread safety during setup/finalize. We should address it at some point.

**Closed by solnic** 2017-07-28 08:35 UTC
