### ISSUE TITLE
Problem with recursive inner joins

### ISSUE THREAD

**Issue by apohllo** [rom-rb/rom-sql#108] opened 2016-11-22 18:09 UTC
The minimal code to reproduce the error is as follows:

```ruby
require 'rom'
require 'rom-repository'

rom = ROM.container(:sql, 'postgres://localhost/test_rom') do |conf|
  conf.default.create_table(:nodes) do
    primary_key :id
    column :name, String, null: false
    column :parent_id, Integer
  end
end

class NodesRepo < ROM::Repository[:nodes]
  commands :create

  def by_id(id)
    nodes.where(id: id)
  end

  def recursive(names)
    query = nodes
    names.each.with_index do |name, index|
      if index == 0
        query = query.prefix("nodes_0").qualified.where("nodes_0__name" => name)
      else
        query = query.prefix("nodes_#{index}").qualified.inner_join(:nodes, "nodes_#{index}_parent_id" => "nodes_#{index-1}_id").
          where("nodes_#{index}__name" => name)
      end
    end
    query
  end
end

nodes_repo = NodesRepo.new(rom)
parent = nodes_repo.create(name: "parent")
child1 = nodes_repo.create(name: "child1", parent_id: parent.id)
child2 = nodes_repo.create(name: "child2", parent_id: parent.id)
grandchild1 = nodes_repo.create(name: "grandchild1", parent_id: child1.id)
grandchild2 = nodes_repo.create(name: "grandchild2", parent_id: child2.id)

# works fine
p nodes_repo.by_id(parent.id).to_a.first
# raises PG::DuplicateAlias: ERROR:  table name "nodes" specified more than once (Sequel::DatabaseError)
p nodes_repo.recursive(%w{parent child1 grandchild1}).to_a
```

**Comment by AMHOL** [comment] 2016-12-06 16:11
Is this your actual use-case? [Nested Set Model](https://en.wikipedia.org/wiki/Nested_set_model) would probably be a better fit if you need to return a subset of child nodes.

As for the issue, I haven't tested it but try calling `#inner_join` with something like: `inner_join("nodes AS nodes_#{index}")`

**Comment by apohllo** [comment] 2016-12-27 16:32
Yes this is a real use-case. I know the nested set model, but here the scenario is a bit different. Usually one node needs to be selected, which is identified by a composite key, based on parent nodes. Thus the most natural (but not most efficient) way of identifying the node is via path of its parents.

**Comment by AMHOL** [comment] 2016-12-27 20:38
OK, cool, did you try the suggested fix at all?

**Comment by apohllo** [comment] 2016-12-27 21:04
A different error is reported:
```
PG::UndefinedTable: ERROR:  relation "nodes as nodes_1" does not exist (Sequel::DatabaseError)
```

**Comment by solnic** [comment] 2017-11-02 00:19
I'm gonna close this one since it is not a bug. It's possible to build a query like that, but using a slightly different approach (I'll try to show how and post it on our forum in the related thread).

**Closed by solnic** 2017-11-02 00:19 UTC
Labels: question

**Comment by apohllo** [comment] 2017-11-02 09:31
Ok, I'm looking forward to see the solution. Thanks.
