### ISSUE TITLE
Multi-Schema database

### ISSUE THREAD

**Issue by alex-lairan** [rom-rb/rom-sql#404] opened 2022-01-18 10:56 UTC
## Describe the bug

Context :
- Postgres
- 2 schema (public, x)

When using a multi-schema database, we have to qualify tables that are not on the current_schema.

e.g 
```ruby
class XFoo< ROM::Relation[:sql]
  schema(Sequel::SQL::QualifiedIdentifier.new('x', 'foo'), as: :x_foo, infer: true) do
    attribute :id, Types::Integer
    attribute :value, Types::Float
    attribute :bar_id, Types::ForeignKey(:bar)

    primary_key :id

    associations do 
      belongs_to :bars, as: :bar, foreign_key: :bar_id
    end
  end
end
```

The line `ROM.env.relations[:x_foo].to_a` don't find the table `"'x'.'foo'"`.

How could I replace the `Sequel::SQL::QualifiedIdentifier.new`?
If this needs more dev, how can I help? :) 

## To Reproduce

Create a database with 2 schemas, one table each.
Create a relation for both tables.

## Expected behavior

I should be able to query `'x'.'foo'` and not `"'x'.'foo'"`

## My environment

- Affects my production application: **YES**
- Ruby version: 2.7.4
- OS: All

**Comment by flash-gordon** [comment] 2022-01-19 06:11
It's a duplicate of https://github.com/rom-rb/rom-sql/issues/163

**Closed by flash-gordon** 2022-01-19 06:11 UTC
Labels: bug, help wanted
